### ISSUE TITLE
Boot delay

### ISSUE THREAD

**Issue by nomandera** [linuxserver/docker-sickgear#2]
There is a sizable delay between

```
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
```

current working theory is that it is related to https://github.com/linuxserver/docker-sickgear/blob/master/root/etc/cont-init.d/30-config#L11-L14

**Comment by aptalca** [comment]
We saw that issue with plex, where there can be hundreds of thousands files in the config folder. For that image, we put in logic that checks the folder permissions to decide whether to chown or not so it only runs if the folder perms are incorrect. It's not the most ideal solution because if a user adds a plugin into one of the subfolders, the perms for that folder may be incorrect unless manually fixed.

I don't know how many files this image has under /app and /config

**Comment by nomandera** [comment]
7735 files in the app folder by default. Existing installs may have 10 times this in the config folder.

I have found what you are talking about

https://github.com/linuxserver/docker-plex/blob/master/root/etc/cont-init.d/40-chown-files

Very much appreciated. Once this initial release passes peer review I will add this change.

**Comment by CHBMB** [comment]
@anoma Want to submit a PR to this?  Or close it?

**Comment by nomandera** [comment]
Did we ever agree on a universal approach to fixing this common problem?

**Comment by CHBMB** [comment]
I thought from reading above you were just going to go with the Plex solution?

**Comment by nomandera** [comment]
It got lost in the mist of time but there was several chats about a couple options for a a generic way to solve this issue whenever it came up (rather than lots of custom solutions).

But TBH I am leaning towards just leaving it alone now since no one but me has noticed its a problem and revisit it when we decide on THE way.

**Comment by nomandera** [comment]
Closing.

No one else has reported this issue and whilst it is real and universal I currently prefer the slow reliable approach than the extra complication of maintaining a workaround. We can revisit later if it becomes a more popular problem.
